name: covidnearme
description: Submit your symptoms and learn about COVID-19 in your area.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  app_settings: ^3.0.1
  connectivity: ^0.4.8+2
  charts_flutter: ^0.9.0
  equatable: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0
  flutter_dotenv: ^2.1.0
  flutter_hud:
    git:
      url: https://github.com/eyro-labs/flutter_hud.git
      ref: 0d5ed29fc2aa97dff2863ab824dba48264048c6a
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.3.4
  flutter_phoenix: ^0.1.0
  flutter_svg: ^0.17.3+1
  font_awesome_flutter: ^8.7.0
  hydrated_bloc: ^3.0.0
  intl: ^0.16.0
  logging: ^0.11.4
  meta: ^1.1.8
  package_info: ^0.4.0+16
  path: ^1.6.4
  path_provider: ^1.6.5
  provider: ^4.0.4
  retrofit: ^1.3.1+1
  searchable_dropdown: ^1.1.2
  share: ^0.6.3+6
  url_launcher: ^5.4.2
  uuid: ^2.0.4

dev_dependencies:
  build_runner: ^1.8.0
  file: ^5.1.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  json_serializable: ^3.2.5
  mockito: ^4.1.1
  pedantic: ^1.8.0
  retrofit_generator: ^1.3.1+9
  test: ^1.9.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/copy/
    - assets/images/
    - assets/images/icons/
